### ISSUE TITLE
Drush aliases

### ISSUE THREAD

**Issue by luismagr** [front-id/dockerizer#4]
Several things about drush aliases

- [x] Generate drush aliases for local environment. The following command should give the initial configuration for the local environment: `  drush site-alias @self --full --with-optional `

- [x]  Allow docker images to access development environments. This is necesary for database and files synchronization

**Comment by capynet** [comment]
El segundo punto creo que dice que se quiere poder entrar en cualquier contenedor no? en ese caso con hacer `expose php` o `expose mariadb` ya puedes meterte en cada maquina

**Comment by luismagr** [comment]
No era eso pero se arregló con el tema de ssh forwarding.

**Comment by luismagr** [comment]
Creo que el primer punto también está ¿no? @capynet

**Comment by capynet** [comment]
yes!
